-- 코드를 작성해주세요
SELECT B.Y AS YEAR, B.SIZE - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA A
JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS SIZE, YEAR(DIFFERENTIATION_DATE) AS Y 
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS B ON YEAR(A.DIFFERENTIATION_DATE) = Y
ORDER BY B.Y, YEAR_DEV

