-- 코드를 입력하세요
SELECT BD.TITLE
       , RE.BOARD_ID
       , RE.REPLY_ID
       , RE.WRITER_ID
       , RE.CONTENTS
       , DATE_FORMAT(RE.CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS BD
INNER JOIN USED_GOODS_REPLY AS RE
        ON BD.BOARD_ID = RE.BOARD_ID
WHERE YEAR(BD.CREATED_DATE) = "2022" 
    AND MONTH(BD.CREATED_DATE) = "10"
ORDER BY CREATED_DATE, TITLE
-- BOARD_ID 공통, TITLE BOARD 에서
-- 나머지 REPLY에서